pipeline {
    agent any

    parameters {
        string (name: 'env', defaultValue: 'dev.yml',  description: 'This is the inventory file for the environment to deploy configuration')
        }

    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/.ansible.cfg"
            }

    

    stages {
        stage("Initial cleanup") {
            steps {
                dir("${WORKSPACE}") {
                deleteDir()
                    }
                }
            }

        stage ('Checkout SCM') {
            steps{
                git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/yemveiser/ansible-configuration-management-3.git'
            }
        }

        stage ('Prepare Ansible For Execution') {
            steps {
            sh 'echo ${WORKSPACE}' 
            sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
            }
        }

        stage ('Run Ansible playbook') {
            steps {
            ansiblePlaybook become: true, colorized: true, credentialsId: 'Private-key', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'inventory/dev.yml', playbook: 'playbooks/site.yml'
            }
        }

        stage ('Clean Workspace after build') {
            steps {
            cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}